### ISSUE TITLE
No global fit drawn

### ISSUE THREAD

**Issue by bjartelund** [harmslab/pytc#63]
Hi,

Thanks for the very nice package, I have been able to fit 3 titrations and blank following the demo. However, the plot just has lines drawn between the points of the individual experiments, with no globally fitted line. What would be the best way to implement a global fit line, or is there some setting that I am missing? 

Kind regards,
Bjarte

**Comment by harmsm** [comment]
Hi Bjarte,

Glad you're using pytc.  I think I understand your question and make a crack at answering it below.  Let me know if I answered the wrong one.  Also, free free to post a code/dataset example if helpful. 

pytc fits each experiment individually, but allows linking of parameters between experiments to allow global fitting.  If you have three experiments, you will end up with three lines, each showing how the global fit goes through that particular experimental dataset.  For example, imagine you fit three experiments with a globally linked Kd and dH, but with other parameters (like the fraction competent) fit individually to each experiment.  All three experiments globally determine the Kd and dH, but because the fraction competent may be different on each experiment, you end up with a different line for each one. 

If you wanted a single line, you would have to link all parameters between the three experimental datasets.  Even then, it would draw a line for every experiment, but the lines would all land exactly on top of one another. 

Here's an example global fit to three replicates and a blank that hopefully illustrates what I mean. 

https://github.com/harmslab/pytc-demos/blob/master/06_global-fit-three-replicates-and-blank.ipynb

Best,

Mike

**Comment by bjartelund** [comment]
Hi Mike,

Thanks for your reply. I was indeed not fixing the fx_competent parameter, and that was giving me the three different lines. Making that a global parameter did indeed give me a single line for the titrations as I wanted. 

Kind regards,

Bjarte

**Comment by harmsm** [comment]
Great, glad that worked!

Mike
